### ISSUE TITLE
I test this script 

### ISSUE THREAD

**Issue by Dmitriy51** [Fairuz-Afdhal/IsPlayerUsingAndroid#2]
does not detect anything.

**Comment by Fairuz-Afdhal** [comment]
Please elaborate..
Please explain how do you use it, how do you test it,etc.

**Comment by Dmitriy51** [comment]
I test you filterscript, but it does not detect anything.... possibly not all android versions samp.
https://github.com/Fairuz-Afdhal/IsPlayerUsingAndroid/tree/master/filterscripts
